language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get install python-numpy python-scipy python-pandas
install:
  - pip install scikit-learn
  - pip install . # Install it self
script: py.test